### ISSUE TITLE
Cant clone the repo

### ISSUE THREAD

**Issue by ajstrand** [gleam-lang/gleam-mode#11]
I've set up gleam with vscode, so it works fine there. 

But I wanted to try gleam with Emacs and got this error:
```bash
git clone --recurse-submodules git@github.com:gleam-lang/gleam-mode
Cloning into 'gleam-mode'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

Any idea why this happens? 

One possible workaround would be to fork the repo. 

Would you want help publishing the code to MELPA?
Im new to emacs/gleam, but I'd be happy to help.

**Comment by akirak** [comment]
You tried to clone the repository via SSH. Did you upload your public key to GitHub? You could use the HTTPS url instead:

```
git clone --recurse-submodules https://github.com/gleam-lang/gleam-mode
```

**Comment by J3RN** [comment]
I believe @akirak is right on this one; sounds like a GitHub authentication issue and using HTTPS should work. Please reopen the issue if that doesn't work for you!
