### ISSUE TITLE
Melpa release

### ISSUE THREAD

**Issue by slondr** [gleam-lang/gleam-mode#20]
Hi, not sure how difficult this would be but installing & upgrading would be much nicer if gleam-mode was available on MELPA

**Comment by J3RN** [comment]
Hey @slondr, thanks for calling that out!  It's definitely something that I've thought about, but I don't think that MELPA would support the current submodule approach used for gleam-mode.  The approach could be changed to, say, download pre-compiled versions of the grammar, though that would take some work.

Currently, my plan is to soft-deprecate gleam-mode in favor of gleam-ts-mode when that is done.  gleam-ts-mode should be perfectly eligible for MELPA.

**Comment by J3RN** [comment]
[`gleam-ts-mode` is now distributed my MELPA](https://github.com/melpa/melpa/pull/9121)

**Comment by tralph3** [comment]
Hi can a package be made for those of us that prefer to not use treesitter? Even the file linked in the readme tries to load treesitter.
