### ISSUE TITLE
Rename `master` to `main`?

### ISSUE THREAD

**Issue by J3RN** [gleam-lang/gleam-mode#7]
Hey there! I'm getting _very_ close to being satisfied with [my rewrite](https://github.com/J3RN/gleam-mode)! :tada: 

I noticed that the main branch over here is named "master". The convention for Gleam repositories seems to be to use the name "main" for the main branch. Should we rename the branch to follow that convention?

**Comment by lpil** [comment]
Well spotted, I'll do that right away.
